apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ .Chart.Name }}-{{ .Values.env }}
  labels:
    app: {{ .Chart.Name }}-{{ .Values.env }}
spec:
  selector:
    matchLabels:
      app: {{ .Chart.Name }}-{{ .Values.env }}
  template:
    metadata:
      labels:
        app: {{ .Chart.Name }}-{{ .Values.env }}
    spec:
      containers:
      - name: {{ .Chart.Name }}-{{ .Values.env }}
        image: atzawada/iam-tools:{{ .Values.tag }}
        imagePullPolicy: Always
        ports:
        - containerPort: 8080
        env:
        - name: IAM_DB_URL
          valueFrom:
            secretKeyRef:
              name: iam-dbcreds-{{ .Values.env }}
              key: url
        - name: IAM_DB_USER
          valueFrom:
            secretKeyRef:
              name: iam-dbcreds-{{ .Values.env }}
              key: username
        - name: IAM_DB_PASSWORD
          valueFrom:
            secretKeyRef:
              name: iam-dbcreds-{{ .Values.env }}
              key: password