apiVersion: v1
kind: Service
metadata:
  name: {{ .Chart.Name }}-{{ .Values.env }}
  labels:
    app: {{ .Chart.Name }}-{{ .Values.env }}
  annotations:
{{ toYaml .Values.service.annotations | indent 4 }}
spec:
  type: LoadBalancer
  loadBalancerIP: {{ .Values.service.loadBalancerIP }}
  ports:
  - port: 8080
    targetPort: 8080
    protocol: TCP
    name: http
  - port: 443
    protocol: TCP
    name: https
  selector:
    app: {{ .Chart.Name }}-{{ .Values.env }}